main:
   path: /
   controller: App\Controller\MainController::main
check_for_updates:
   path: /webApi/structure/updates/check
   controller: App\Controller\WebApiController::hasUpdates
update_structure:
   path: /webApi/structure/update
   controller: App\Controller\WebApiController::updateStructure
device_action:
   path: /webApi/device/{action}
   requirements:
      action: 'list|link|unlink'
   controller: App\Controller\WebApiController::deviceAction
get_status:
   path: /webApi/status/{peripheralType}
   requirements:
      peripheralType: 'sensor|actuator|controller|element|room'
   controller: App\Controller\WebApiController::getStatus
sync_log:
   path: /webApi/log/{peripheralType}/{logType}
   requirements:
      peripheralType: 'sensor|actuator|controller|element|room'
      logType: 'int|bit|auto'
   controller: App\Controller\WebApiController::syncLog
