check_for_updates:
   path: /webApi/main/getUpdates
   controller: App\Controller\WebApiController::hasUpdates
get_structure:
   path: /webApi/objects/getDevices
   controller: App\Controller\WebApiController::getDevices
